Repository scroll-tech/scroll, pull requests merged in 2024-02, with the labels that each got.

#1104 fix(sender): enforce single instance for each sender type
  common/version/version.go
  rollup/cmd/gas_oracle/app/app.go
  rollup/cmd/rollup_relayer/app/app.go
  rollup/internal/controller/relayer/common.go
  rollup/internal/controller/relayer/l1_relayer.go
  rollup/internal/controller/relayer/l1_relayer_test.go
  rollup/internal/controller/relayer/l2_relayer.go
  rollup/internal/controller/relayer/l2_relayer_test.go
  rollup/internal/controller/sender/sender.go
  rollup/internal/controller/sender/sender_test.go
  rollup/tests/gas_oracle_test.go
  rollup/tests/rollup_test.go
Labels: bug, bump-version

#1103 fix(bridge-history): use msg.sender encoded in message field of SentMessage event
  bridge-history-api/go.mod
  bridge-history-api/go.sum
  bridge-history-api/internal/logic/l1_event_parser.go
  bridge-history-api/internal/logic/l2_event_parser.go
  common/version/version.go
Labels: bug, bump-version

#1094 fix(contracts): OZ-L01 Implementation Keeps Functionalities for Deprecated Variables
  contracts/src/L1/gateways/IL1GatewayRouter.sol
  contracts/src/L1/gateways/L1GatewayRouter.sol
  contracts/src/L2/gateways/IL2GatewayRouter.sol
  contracts/src/L2/gateways/L2GatewayRouter.sol
  contracts/src/test/L1GatewayRouter.t.sol
  contracts/src/test/L2GatewayRouter.t.sol
Labels: bug

#1096 fix(contracts): OZ-N02 Renaming Opportunities
  contracts/src/L1/rollup/L1MessageQueueWithGasPriceOracle.sol
Labels: bug

#1097 fix(contracts): OZ-N03 Mismatch Between Interface and Implementation
  contracts/src/L1/rollup/IL1MessageQueue.sol
  contracts/src/L1/rollup/IL1MessageQueueWithGasPriceOracle.sol
  contracts/src/L1/rollup/L1MessageQueueWithGasPriceOracle.sol
Labels: bug

#1099 fix(contracts): OZ-N08 Deprecated Variables Are Still Being Assigned Values
  contracts/src/L1/gateways/L1StandardERC20Gateway.sol
  contracts/src/L2/gateways/L2StandardERC20Gateway.sol
Labels: bug

#1095 refactor(contracts): OZ-N01 Different Frameworks Are Used Concurrently in the Protocol
  contracts/package.json
Labels: enhancement

#1098 docs(contracts): OZ-N07 Missing or Inconsistent Documentation
  contracts/src/L1/gateways/L1CustomERC20Gateway.sol
  contracts/src/L1/gateways/L1ERC1155Gateway.sol
  contracts/src/L1/gateways/L1ERC721Gateway.sol
  contracts/src/L1/gateways/L1ETHGateway.sol
  contracts/src/L1/gateways/L1StandardERC20Gateway.sol
  contracts/src/L1/gateways/L1WETHGateway.sol
  contracts/src/L1/gateways/usdc/L1USDCGateway.sol
  contracts/src/L1/rollup/IL2GasPriceOracle.sol
  contracts/src/L2/gateways/L2ETHGateway.sol
  contracts/src/L2/gateways/L2GatewayRouter.sol
  contracts/src/L2/gateways/L2StandardERC20Gateway.sol
Labels: documentation

#1108 fix(sender): add gas limit when querying access list
  common/version/version.go
  rollup/internal/controller/sender/estimategas.go
Labels: bump-version

#1146 fix(gas-oracle): update gas price with diff at least 1 wei
  common/version/version.go
  rollup/internal/controller/relayer/l1_relayer.go
  rollup/internal/controller/relayer/l2_relayer.go
Labels: bump-version

#1134 refactor(event-watcher): remove duplicated L2 message syncing features
  common/version/version.go
  rollup/cmd/event_watcher/app/app.go
  rollup/cmd/rollup_relayer/app/app.go
  rollup/conf/config.json
  rollup/internal/config/l2.go
  rollup/internal/controller/watcher/common.go
  rollup/internal/controller/watcher/l2_watcher.go
  rollup/internal/controller/watcher/l2_watcher_test.go
  rollup/internal/controller/watcher/watcher_test.go
Labels: bump-version
